on: push
name: Check Assignment

jobs:
  check-allowed-files:
    runs-on: ubuntu-latest
    container:
      image: python:3.9-slim
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Check Files
      run: python check_allowed_files.py "hw-01.qmd" "README.md" "data/*" "images/*" "check_allowed_files.py"

  check-renders:
    env:
      GITHUB_PAT: ${{ secrets.GH_PAT }}
    runs-on: ubuntu-latest
    container:
      image: python:3.9-slim
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python and Quarto environment
      run: |
        apt-get update && apt-get install -y wget
        wget -q -O quarto.deb https://github.com/quarto-dev/quarto-cli/releases/download/v1.1.189/quarto-1.1.189-linux-amd64.deb
        dpkg -i quarto.deb
        python -m pip install --upgrade pip
        pip install notebook
    - name: Render html
      run: quarto render hw-01.qmd
    - name: Create artifacts
      uses: actions/upload-artifact@v2
      with:
        name: hw-01-html
        path: hw-01.html
